# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AriaSwiftyChain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AriaSwiftyChain
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCocoa'

  target 'AriaSwiftyChainTests' do
    # Pods for testing
  end

end
