# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OCExample
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'RxCocoa'

  target 'OCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCExampleUITests' do
    # Pods for testing
  end

end
